### ISSUE TITLE
File Uploaded

### ISSUE THREAD

**Issue by alagaddonjuan** [ashishpatel0720/moodle#1]
Great work but i see somethings hasn't been included like 
when the file has been uploaded by the student it can't be viewed by the lecturer, i mean a link to download. and how is it going to be graded

**Comment by pateash** [comment]
Did you see the website


_Sent from my Xiaomi Redmi 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pateash** [comment]
You can just create account at 
Manitmoodle.tk , as there is no email verification...

_Sent from my Xiaomi Redmi 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by pateash** [comment]
Oh, sorry I got it, thank you for pointing it out

**Comment by shermix** [comment]
I could not see any html file or live link to evaluate this project, I would need this project as an inspiration for a school project.

**Comment by feynon** [comment]
The database files seem to be missing.

**Comment by pateash** [comment]
Hi, let me check it on weekend

**Comment by feynon** [comment]
Sure, that's cool. I got it running on XAMPP server anyways.

**Comment by pateash** [comment]
thats good to hear, Please start my below project
https://github.com/codingtools/cdt
